language: node_js
sudo: required
node_js:
  - stable


env:
  - CONTAINER_NAME=lbuzz/nightmare-server

services:
  - docker


script:
  - npm run build
  - docker build -t $CONTAINER_NAME .



after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$CONTAINER_NAME";
    fi
